fixed help, and many other errors

diff --git a/net-tool-v3 b/net-tool-v3
--- a/net-tool-v3
+++ b/net-tool-v3
@@ -1,10 +1,13 @@
 #!/bin/bash
 function help_screen () {
-  echo "command [type] url [options]"
+  echo "Usage: script [option]"
   echo "    -h for this screen"
-  echo "types are:"
-  echo "    -c check connection to internet"
-  echo "    -w watch interface"
+  echo "    -c check if srcipt's external commands are installed"
+  echo ""
+  echo "    -d set device, 'list' for a list to select from"
+  echo "    -w set wifi, 'list' for a list to select from"
+  echo "    -t test connection to internet"
+  echo "    -m monitor interface"
   echo "    -r reset interface"
   echo "    -a show ip adress"
   echo "    -s sync date/time"
@@ -26,21 +29,21 @@ function command_print () { echo "command checks"
   if [ ! "$(type -t file)" = "" ]; then echo "file: yes"; else echo "file: no";fi
   if [ ! "$(type -t grep)" = "" ]; then echo "grep: yes"; else echo "grep: no";fi
   if [ ! "$(type -t identify)" = "" ]; then echo "identify: yes"; else echo "identify: no";fi
-  if [ ! "$(type -t qalc)" = "" ]; then echo "qalc: yes"; else echo "qalc: no";fi
   exit 0 ;} ## function command_check () {
-ping_check1 () { ping_result1=echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1"" ;}
-ping_check2 () { ping_result2=curl --silent --head http://www.google.com/ |egrep '20[0-9] Found|30[0-9] Found' > /dev/null ;}
-line_start () { ctime="$(date +%k:%M:%S)" ;}
+function ping_check () { 
+  echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1"" ; ping_result1=$?
+  curl --silent --head http://www.google.com/ |grep '20[0-9] Found|30[0-9] Found' > /dev/null ; ping_result2=$?
+  } ## function ping_check1 () { 
+function line_start () { ctime="$(date +%k:%M:%S)" ;}
 function check {
   line_start ; o=$ctime # starts output with time of execution
-  ping_check1
+  ping_check
   case "$ping_result1" in
     0) o+=" - C1:Internet" ; c_c1=0;;
     1) o+=" - C1:No Internet" ; c_c1=1;;
     2) o+=" - C1:No Connection" ; c_c1=2;;
-    *) echo "function check - check #1: ERROR, unexpected resualt"
+    *) echo "function check - check #1: ERROR, unexpected resualt '$ping_result1'"
   esac ## case "$ping_result1" in
-  ping_check2
   case "$ping_result2" in
     0) o+=" - C2:No Internet" ; c_c2=0;;
     1) o+=" - C2:Internet" ; c_c2=1;;
@@ -61,7 +64,7 @@ function monitor {
       esac ## case $var in
       if [ $w_c2 != $ss_1 ]; then step=0; delay=1; ss_1="$w_c2" ;fi ## saving w_c2 for next loop and reset interval length
       if [ $w_c2 != "0" ]; then
-        ping_check1 ; case $ping_result1 in ## check #3, pings internet
+        ping_check ; case $ping_result1 in ## check #3, pings internet
           0) o+=" - C3:Internet";;
           1) o+=" - C3:No Internet";;
           2) o+=" - C3:No Connection";;
@@ -69,7 +72,7 @@ function monitor {
         esac ## case $ping_check1 in
         if [ $w_c3 != $ss_2 ]; then step=0; delay=1; ss_2="$w_c3" ;fi ## saving w_c3 for next loop and reset interval length
         if [ $w_c3 = "0" ]; then
-          ping_check2 ; case "$ping_result2" in ## check #4, pings internet
+          case "$ping_result2" in ## check #4, pings internet
             0) o+=" - C4:No Internet";;
             1) o+=" - C4:Internet";;
             2) o+=" - C4:No Connection";;
@@ -88,8 +91,9 @@ function reset {
   nmcli con down "$con_name"
   sleep 10s
   result="starting"
+  step=0 ; delay=5
   while [ ! $result = "0" ]; do
-    step=0 ; delay=5 ; interval
+    interval
     echo "atempting reconection"
     nmcli con up "$con_name"
     result=$?
@@ -123,7 +127,7 @@ function con_select () { ## deevice selection
 while getopts ":hcd:w:tmras" opt; do case $opt in
     #--------# Help / Command Check #--------#
     h) help_screen ; exit 0 ;;
-    c) command_check "print" ; exit 0 ;;
+    c) command_print ; exit 0 ;;
     #--------# Setting values #--------#
     d) if [ ! "${OPTARG}" = "list" ]; then declare -r dev_name="${OPTARG}"
     else dev_select ;fi ;;
